---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: "EXEMPLO DE REGISTER"
    shell: "date -u"
    register: linux_date

  - name: "EXIBINDO REGISTER"
    debug:
      msg: "{{ linux_date.start }}"
